### ISSUE TITLE
FinClip 小程序游戏体验评测报告

### ISSUE THREAD

**Issue by MarkBurt** [finogeeks/finclip-ios-demo#12]
接入过程：
    1.使用微信开发者工具编写完代码
    2.使用FinClip IDE 导入项目并选择小游戏（测试）
    3.编译运行
    4.上传后转至Finclip管理平台进行审核上架操作
使用效果：
   1.于微信小游戏无异
   2.会出现断触的情况不知道是不是我手机的原因（手机为iPhone 12 pro）
同类技术分析：
  1.当然是免费啦
  2.集成起来超级简单（加鸡腿）
  3.同阿里的小程序容器相比来看没有云函数
后续建议：
      IDE方面（我的为Mac Book M2)：
           1.创建小游戏时可以选择APP ID 而不是在上传时才选择APP ID
           2.创建小游戏时可以选择以模版引擎创建(COCOS,Three.js,Layabox,Unity,...)
      代码方面：
           1.可以加入分包显示（打包上传时）
           2.可以加入小程序云开发
       其他方面：
           哈哈 因为我使用的Flutter 构建的项目 还是希望可以出点Flutter的API ，不过在使用Flutter集成finclip 的时候iPhone显示小程序右上角的图标底色居然不是白色的是粉色的。 顺带一提不知道那个小程序加载的时候那个finclip 可以单独设置就好啦 或者提供几个可以选择的那种也可以 嘿嘿

**Comment by MarkBurt** [comment]
顺带一提我的小程序APPID：
63e218893dc3390001ffbb38

**Comment by MarkBurt** [comment]
还有一个忘记啦：
  小程序的名称限制可以调一下嘛 两三个字的小游戏有很多呀比如：跳一跳,找不同，数独，拆弹猫.... (这都不是我的均在微信小程序推荐内得知)

**Comment by Haley-Wong** [comment]
感谢你的认可和优化建议。
我们的小游戏功能还在持续优化和迭代，后续持续关注哦！

**Comment by Haley-Wong** [comment]
小程序名称长度的限制，我们会在最近一两迭代内优化掉。感谢建议！
